/**
 * e-Shram Mock Form PDF Generator
 * Generates mock e-Shram registration form PDF with benefits summary
 */

const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

/**
 * Generate mock e-Shram form PDF
 * @param {Object} options - PDF generation options
 * @param {Object} options.formData - Filled form data
 * @param {Object} options.userEmail - User's email
 * @returns {Promise<Buffer>} PDF buffer
 */
async function generateEShramPDF(options) {
  const { formData, userEmail } = options;

  // Validate required inputs
  if (!formData) {
    throw new Error('formData is required for PDF generation');
  }

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: 'A4',
      });

      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Helper function to add section
      const addSection = (title, content) => {
        doc.fontSize(14).font('Helvetica-Bold').text(title, { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(10).font('Helvetica');
        
        if (typeof content === 'string') {
          doc.text(content);
        } else if (Array.isArray(content)) {
          content.forEach(item => {
            doc.text(`• ${item}`, { indent: 20 });
          });
        }
        doc.moveDown(1);
      };

      // Header
      doc.fontSize(18).font('Helvetica-Bold').text('Mock e-Shram Registration Form', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(10).font('Helvetica').text('FOR EDUCATIONAL PURPOSES ONLY - NOT AN OFFICIAL REGISTRATION', { align: 'center', color: '#FF0000' });
      doc.moveDown(1);

      // Disclaimer
      doc.fontSize(9).font('Helvetica-Oblique').text('⚠️ This is a mock form generated by PaisaBuddy for educational purposes only. It is not an official e-Shram registration document.', { color: '#FF6600' });
      doc.moveDown(1);

      // Personal Information
      addSection('Personal Information', [
        `Name: ${formData.name || 'N/A'}`,
        `Mobile Number: ${formData.mobile || 'N/A'}`,
        `Email: ${formData.email || 'N/A'}`,
        `Age/Date of Birth: ${formData.ageOrDob || 'N/A'}`,
        `State: ${formData.state || 'N/A'}`,
        `Occupation: ${formData.occupation || 'N/A'}`,
        `Annual Income Range: ${formData.incomeRange || 'N/A'}`,
      ]);

      // Benefits Summary
      addSection('e-Shram Benefits Summary for Unorganized Workers', [
        'Accident Insurance Coverage: Up to ₹2 Lakh in case of accidental death or permanent disability',
        'Pension Scheme: Eligible for Pradhan Mantri Shram Yogi Maan-Dhan (PM-SYM) after 60 years',
        'Skill Development: Access to skill development programs and training',
        'Health Insurance: Linkage to PM-JAY (Ayushman Bharat) scheme',
        'Maternity Benefits: For female workers under certain schemes',
        'Disability Benefits: Support through various social security schemes',
        'Education Benefits: Scholarships and education support for children',
      ]);

      // Next Steps
      addSection('Next Steps (For Real Registration)', [
        'Visit the official e-Shram portal: https://eshram.gov.in',
        'Provide Aadhaar number and mobile number linked to Aadhaar',
        'Complete the registration with accurate personal and work details',
        'Receive your e-Shram card (12-digit Universal Account Number - UAN)',
        'Access various social security benefits through the e-Shram portal',
      ]);

      // Footer
      doc.moveDown(2);
      doc.fontSize(8).font('Helvetica').text(`Generated on: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}`, { align: 'center' });
      doc.text(`For: ${userEmail || 'User'}`, { align: 'center' });
      doc.text('Generated by PaisaBuddy - Financial Coach for Gig Workers', { align: 'center' });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

module.exports = {
  generateEShramPDF,
};

